### DISCUSSION TITLE
ansible-lint not triggered during pre-commit hook in Trunk CLI

### DISCUSSION THREAD

**Discussion by howmuch515** [trunk-io/docs#403] [Bugs]
Hi Trunk team,

I'm encountering an issue where `ansible-lint` does not run during the pre-commit hook, even though it works correctly when running `trunk check` manually.

## Setup

- Trunk CLI version: `1.22.12`
- `trunk.yaml` configuration:

    ```yaml
    version: 0.1
    cli:
      version: 1.22.12
    plugins:
      sources:
        - id: trunk
          ref: v1.6.8
          uri: https://github.com/trunk-io/plugins
    lint:
      enabled:
        - markdownlint@0.44.0
        - ansible-lint@25.2.1
      triggers:
        - linters:
            - ansible-lint
          paths:
            - ansible
          targets:
            - ansible
    actions:
      disabled:
        - trunk-announce
        - trunk-check-pre-push
        - trunk-fmt-pre-commit
      enabled:
        - trunk-upgrade-available
        - trunk-check-pre-commit
    runtimes:
      enabled:
        - node@18.20.5
        - python@3.10.8
    ```

## Steps to Reproduce

1. Set up git hooks:
    
    ```bash
    trunk git-hooks sync
    ```

2. Introduce a deliberate linting issue by using a short module name:
    
    ```yaml
    - name: Ensure ~/.config directory exists
      file:
        path: "{{ ansible_env.HOME }}/.config/"
        state: directory
        mode: "0755"
    ```

3. Run `trunk check` manually:
    
    ```bash
    trunk check
    ```
    Output:
    ```
    ansible/roles/set_config/tasks/main.yml:10:3
      Use `ansible.builtin.file` or `ansible.legacy.file` instead.
    ✖ 1 new lint issue
    ```

4. Commit the changes:
    
    ```bash
    git commit -am "test"
    ```
    Output:
    ```
    Checked 1 modified file
    ✔ No issues
    ```

## Observations

- The manual `trunk check` correctly identifies the linting issue.
- The pre-commit hook does not detect the same issue.
- The pre-commit hook runs the following command:
  
    ```bash
    trunk check -n -t "git-commit" --index-file '${env.GIT_INDEX_FILE}' --upstream=HEAD
    ```

- Running this command manually also fails to detect the issue:

    ```bash
    trunk check -n -t "git-commit" --index-file .git/index --upstream=HEAD
    ```

- Omitting the `--index-file` flag allows the issue to be detected:

    ```bash
    trunk check -n -t "git-commit" --upstream=HEAD
    ```

## Conclusion

It appears that specifying the `--index-file` flag causes `ansible-lint` to skip linting certain files during the pre-commit hook.  
Is there a recommended way to ensure `ansible-lint` runs correctly during pre-commit checks?

Any insights or suggestions would be greatly appreciated.
