### DISCUSSION TITLE
Enable Typescript typecheck before push

### DISCUSSION THREAD

**Discussion by paulvanbrenk** [trunk-io/docs#406] [Q&A]
I've been trying to configure `tsc` as a linter to typecheck before we push. This is how far I've come. but now I'm stuck. We run nextjs, and there build command takes too long as a pre-push hook

```yaml
lint:
  enabled:
   # other linters
    - tsc
  definitions:
    - name: tsc
      files: [typescript]
      commands:
        - name: tsc
          run: npm run type-check
          success_codes: [0, 1]
          output: pass_fail 
actions:
  enabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trunk-upgrade-available
tools:
  enabled:
    - tsc@5.8.3
```
